# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: yey
builds:
  - dir: src
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - format: tar.gz
    wrap_in_directory: false
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^chore"
brews:
  - name: joy
    tap:
      owner: nestoca
      name: homebrew-tap
    homepage: "https://github.com/nestoca/joy-cli"
    description: "A CLI for managing and deploying applications"
    license: "MIT"
