# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: joy
builds:
  - dir: cmd/joy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -X "main.version=v{{ trimprefix .Version "v" }}"
archives:
  - formats:
      - tar.gz
    wrap_in_directory: false
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^chore"
      - "^ci"
brews:
  - name: joy
    repository:
      owner: nestoca
      name: homebrew-public
    homepage: "https://github.com/nestoca/joy"
    description: "A CLI for happily managing and deploying applications"
    license: "MIT"
nfpms:
  - package_name: joy
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: nestoca
    homepage: https://github.com/nestoca/joy
    description: |-
      A CLI for happily managing and deploying applications
    license: MIT
    maintainer: Mathieu Frenette <mathieu.frenette@nesto.ca>
    formats:
      - deb
    dependencies:
      - git
