apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: 
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- if .Values.commonLabels }}
        {{- toYaml .Values.commonLabels | nindent 4 }}
        {{- end }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      securityContext:
        fsGroup: 65532
      containers:
        - name: main
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
          image: '{{ .Values.image }}:{{ .Values.version }}'
          imagePullPolicy: IfNotPresent
          ports:
            - name: health
              containerPort: 3000
              protocol: TCP
          readinessProbe: 
            failureThreshold: 6
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 1
          resources: {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
