apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: health
      protocol: TCP
      name: health
  selector:
    release: {{ .Release.Name }}
