name: Build, Test and Publish

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3.3.1
        with:
          go-version-file: go.mod
          # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
          cache: true
          # Used to specify the path to a dependency file - go.sum
          cache-dependency-path: go.sum

      - name: Setup dependencies
        run: make setup

      - name: Run tests w/ Coverage
        run: make test-cov

      - name: Build cli binary
        run: make build

  publish:
    needs:
      - test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Get build info
        id: info
        uses: nestoca/actions/get-build-info@v1

      - name: Setup Go environment
        uses: actions/setup-go@v3.3.1
        with:
          go-version-file: go.mod
          # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
          cache: true
          # Used to specify the path to a dependency file - go.sum
          cache-dependency-path: go.sum

      - name: Tag commit
        uses: silphid/actions/tag-commit@v1
        with:
          tag: ${{ steps.info.outputs.git-tag }}

      - name: Release new CLI version
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
